WEBDOCK.component().register(function(exports){
    var api,router;
    var data={loading:true,saving:{youtube:false,facebook:false},testing:{youtube:false,facebook:false},connecting:{youtube:false,facebook:false},encryptionReady:false,requiredEnvironmentVariable:'DAVVAG_PROVIDER_SECRET',errors:[],info:[],providers:{youtube:providerForm('youtube'),facebook:providerForm('facebook')}};
    exports.vue={data:data,methods:{go:go,save:save,test:test,connect:connect,disconnect:disconnect,statusClass:statusClass},onReady:init};exports.onReady=function(){};
    function providerForm(provider){return{provider:provider,account_name:'',account_id:'',page_id:'',client_id:'',client_secret:'',api_key:'',access_token:'',refresh_token:'',status:'disconnected',has_client_secret:false,has_api_key:false,has_access_token:false,has_refresh_token:false,last_tested_at:'',last_error:''};}
    function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');load();}
    function load(){data.loading=true;api.services.GetProviderSettings({}).then(function(r){data.loading=false;if(!r.success)return fail(message(r,'Provider settings could not be loaded.'));var x=r.result||{};data.encryptionReady=!!x.encryption_ready;data.requiredEnvironmentVariable=x.required_environment_variable||'DAVVAG_PROVIDER_SECRET';merge('youtube',x.providers&&x.providers.youtube);merge('facebook',x.providers&&x.providers.facebook);if(String(location.hash||'').indexOf('oauth=')>=0)ok('Provider account connected. Test the connection to verify API access.');}).error(function(){data.loading=false;fail('Provider settings could not be loaded.');});}
    function merge(provider,row){var form=providerForm(provider);row=row||{};Object.keys(form).forEach(function(k){if(row[k]!==undefined&&row[k]!==null)form[k]=row[k];});data.providers[provider]=form;}
    function payload(provider){var f=data.providers[provider];return{provider:provider,account_name:f.account_name,account_id:f.account_id,page_id:f.page_id,client_id:f.client_id,client_secret:f.client_secret,api_key:f.api_key,access_token:f.access_token,refresh_token:f.refresh_token};}
    function save(provider,done){if(data.saving[provider])return;data.saving[provider]=true;api.services.SaveProviderSettings(payload(provider)).then(function(r){data.saving[provider]=false;if(!r.success){fail(message(r,'Provider settings could not be saved.'));if(done)done(false);return;}merge(provider,r.result);ok(label(provider)+' settings saved securely.');if(done)done(true);}).error(function(){data.saving[provider]=false;fail('Provider settings could not be saved.');if(done)done(false);});}
    function test(provider){if(data.testing[provider])return;data.testing[provider]=true;api.services.TestProvider({provider:provider}).then(function(r){data.testing[provider]=false;if(r.success){ok(message(r,label(provider)+' connection succeeded.'));load();}else fail(message(r,label(provider)+' connection failed.'));}).error(function(){data.testing[provider]=false;fail(label(provider)+' connection failed.');});}
    function connect(provider){if(data.connecting[provider])return;data.connecting[provider]=true;save(provider,function(saved){if(!saved){data.connecting[provider]=false;return;}api.services.StartProviderOAuth({provider:provider}).then(function(r){data.connecting[provider]=false;if(!r.success||!r.result||!r.result.authorize_url)return fail(message(r,'OAuth could not be started.'));window.location.href=r.result.authorize_url;}).error(function(){data.connecting[provider]=false;fail('OAuth could not be started.');});});}
    function disconnect(provider){if(!confirm('Disconnect '+label(provider)+' and remove its stored tokens?'))return;api.services.DisconnectProvider({provider:provider}).then(function(r){if(r.success){merge(provider,r.result);ok(label(provider)+' disconnected.');}else fail(message(r,'Provider could not be disconnected.'));});}
    function go(path){if(router&&router.appNavigate)router.appNavigate('../'+path);}function label(provider){return provider==='youtube'?'YouTube':'Facebook';}function statusClass(v){return'lm-badge '+String(v||'disconnected').toLowerCase();}function message(r,d){return r&&r.result&&r.result.message?r.result.message:(r&&typeof r.result==='string'?r.result:d);}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
