<?php
namespace davvag_credit_points;
require_once dirname(__DIR__,2)."/lib/CreditServiceSupport.php";
class CreditLedgerApiService {
    private function call($res,$fn){try{return$fn();}catch(\Throwable$e){return CreditServiceSupport::fail($res,$e);}}
    private function admin(){return CreditServiceSupport::requireAdmin();}
    private function body($req){return CreditServiceSupport::body($req);}
    public function postBalance($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);$p=CreditServiceSupport::profile();$target=CreditServiceSupport::isAdmin()?intval(CreditServiceSupport::value($b,"profile_id",$p->id)):intval($p->id);return(new CreditLedgerService())->summary($target,CreditServiceSupport::value($b,"program_code","CREDIT"));});}
    public function postCanAfford($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);$p=CreditServiceSupport::profile();$target=CreditServiceSupport::isAdmin()?intval(CreditServiceSupport::value($b,"profile_id",$p->id)):intval($p->id);return(new CreditLedgerService())->canAfford($target,CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::value($b,"program_code","CREDIT"));});}
    public function postTransaction($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->transactionById(CreditServiceSupport::value($b,"transaction_id",0));});}
    public function postCredit($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->credit(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,CreditServiceSupport::value($b,"source_app","credit-ledger-api"),CreditServiceSupport::value($b,"reference_type","external"),CreditServiceSupport::value($b,"reference_id","manual"),CreditServiceSupport::value($b,"description","Credit adjustment")),CreditServiceSupport::value($b,"source_type","ADMIN"),CreditServiceSupport::value($b,"expires_at",null));});}
    public function postDebit($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->debit(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,CreditServiceSupport::value($b,"source_app","credit-ledger-api"),CreditServiceSupport::value($b,"reference_type","external"),CreditServiceSupport::value($b,"reference_id","manual"),CreditServiceSupport::value($b,"description","Credit debit")));});}
    public function postReserve($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->reserve(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,CreditServiceSupport::value($b,"source_app","credit-ledger-api"),CreditServiceSupport::value($b,"reference_type","external"),CreditServiceSupport::value($b,"reference_id","reservation"),CreditServiceSupport::value($b,"description","Reserve credits")),CreditServiceSupport::value($b,"expires_at",null));});}
    public function postCaptureReservation($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->captureReservation(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"reservation_id",0),CreditServiceSupport::context($b,CreditServiceSupport::value($b,"source_app","credit-ledger-api"),"reservation",CreditServiceSupport::value($b,"reservation_id",0),CreditServiceSupport::value($b,"description","Capture credit reservation")));});}
    public function postReleaseReservation($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->releaseReservation(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"reservation_id",0),CreditServiceSupport::idempotency($b,"release"));});}
    public function postUnlockLesson($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->unlockLesson(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"lesson_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,CreditServiceSupport::value($b,"source_app","lesson-manager"),"lesson",CreditServiceSupport::value($b,"lesson_id",0),CreditServiceSupport::value($b,"description","Unlock paid lesson")));});}
    public function postReconcileWallet($req,$res){return$this->call($res,function()use($req){$this->admin();$b=$this->body($req);return(new CreditLedgerService())->reconcile(CreditServiceSupport::value($b,"wallet_id",0));});}
}
?>
