WEBDOCK.component().register(function (exports) {
    var api, sync, analytics, ai;
    var state = {channelId:"",channels:[],days:28,loading:false,syncing:false,planning:false,dashboard:null,analyticsStatus:null,plan:null,error:"",info:""};
    exports.vue={data:state,methods:{load:load,switchChannel:switchChannel,setDays:setDays,runInitial:function(){runSync("RunInitialSync");},runDaily:function(){runSync("RunDailySync");},generatePlan:generatePlan,openVideos:function(){navigate("videos");},openRecommendations:function(){navigate("recommendations");},openStudio:function(){navigate("intelligence");},openChannels:function(){navigate("channels");},formatNumber:formatNumber,formatMinutes:formatMinutes,formatDuration:formatDuration,formatAnalyticsNumber:formatAnalyticsNumber,formatAnalyticsMinutes:formatAnalyticsMinutes,formatAnalyticsDuration:formatAnalyticsDuration,formatDate:formatDate,barHeight:barHeight},onReady:function(){initialize();}};
    exports.onReady=function(){};
    function initialize(){api=exports.getComponent("api");sync=exports.getComponent("youtube-sync");analytics=exports.getComponent("youtube-analytics");ai=exports.getComponent("ai-orchestrator");state.channelId=query("channelId")||window.localStorage.getItem("ytg.selectedChannelId")||"";if(!state.channelId){state.error="Select a channel workspace first.";return;}if(!api||!sync){state.error="Required services are not loaded.";return;}window.localStorage.setItem("ytg.selectedChannelId",state.channelId);api.services.ListChannels({}).then(function(response){if(response.success){state.channels=response.result.channels||[];}});load();}
    function switchChannel(){if(!state.channelId){return;}window.localStorage.setItem("ytg.selectedChannelId",state.channelId);state.dashboard=null;state.plan=null;load();}
    function load(preserveMessages){if(state.loading){return;}state.loading=true;if(!preserveMessages){state.error="";state.info="";}api.services.GetDashboard({channelId:state.channelId,days:state.days}).then(function(response){state.loading=false;if(response.success){state.dashboard=response.result;}else{state.error=responseMessage(response,"Dashboard could not be loaded.");}}).error(function(){state.loading=false;state.error="Dashboard could not be loaded.";});if(analytics){analytics.services.GetAnalyticsStatus({channelId:state.channelId}).then(function(response){if(response.success){state.analyticsStatus=response.result;}});}}
    function setDays(days){state.days=days;load();}
    function runSync(method){if(state.syncing){return;}state.syncing=true;state.error="";state.info="";sync.services[method]({channelId:state.channelId}).then(function(response){state.syncing=false;if(response.success){var result=response.result||{};var message=result.message||"Synchronization completed.";if(result.warnings&&result.warnings.length){state.error=message;}else{state.info=message;}load(true);}else{state.error=responseMessage(response,"Synchronization failed.");}}).error(function(){state.syncing=false;state.error="Synchronization failed.";});}
    function generatePlan(){if(!ai||state.planning){return;}state.planning=true;state.error="";ai.services.GenerateChannelPlan({channelId:state.channelId}).then(function(response){state.planning=false;if(response.success){state.plan=response.result;state.info=response.result.message||"Weekly plan created.";}else{state.error=responseMessage(response,"Weekly plan could not be created.");}}).error(function(){state.planning=false;state.error="Weekly plan could not be created.";});}
    function query(name){var match=new RegExp("[?&]"+name+"=([^&#]*)").exec(window.location.hash||"");return match?decodeURIComponent(match[1].replace(/\+/g," ")):"";}
    function navigate(path){var routes=exports.getShellComponent("soss-routes");var suffix=path.indexOf("?")>=0?"&":"?";path+=suffix+"channelId="+encodeURIComponent(state.channelId);if(routes&&routes.appNavigate){routes.appNavigate("../"+path);}else{window.location.hash="#/app/youtube-growth-agent/"+path;}}
    function formatNumber(value){return Number(value||0).toLocaleString();}
    function formatMinutes(value){var minutes=Number(value||0);return minutes.toLocaleString(undefined,{maximumFractionDigits:1})+" min";}
    function formatDuration(value){var seconds=Math.max(0,Math.round(Number(value||0)));var min=Math.floor(seconds/60);var sec=seconds%60;return min+":"+(sec<10?"0":"")+sec;}
    function hasAnalyticsData(){return !!(state.dashboard&&state.dashboard.hasAnalyticsData);}
    function formatAnalyticsNumber(value){return hasAnalyticsData()?formatNumber(value):"N/A";}
    function formatAnalyticsMinutes(value){return hasAnalyticsData()?formatMinutes(value):"N/A";}
    function formatAnalyticsDuration(value){return hasAnalyticsData()?formatDuration(value):"N/A";}
    function formatDate(value){if(!value){return"Not yet";}var date=new Date(String(value).replace(" ","T"));return isNaN(date.getTime())||date.getFullYear()<=1970?"Not yet":date.toLocaleString();}
    function barHeight(row){if(!state.dashboard||!state.dashboard.daily||!state.dashboard.daily.length){return"2%";}var max=1;state.dashboard.daily.forEach(function(item){max=Math.max(max,Number(item.views||0));});return Math.max(2,Math.round((Number(row.views||0)/max)*100))+"%";}
    function responseMessage(response,fallback){if(response&&response.result){if(typeof response.result==="string"){return response.result;}if(response.result.message){return response.result.message;}}return fallback;}
});
