WEBDOCK.component().register(function(exports){
 var api,router;var data={courses:[],subjects:[],lessons:[],profiles:[],rows:[],results:[],attempts:[],filters:{course_id:'',subject_id:'',lesson_id:'',student_id:'',teacher_id:'',search:'',completion_status:'',date_from:'',date_to:''},errors:[],info:[]};
 exports.vue={data:data,methods:{go:go,courseChanged:courseChanged,subjectChanged:subjectChanged,subjectsForCourse:subjectsForCourse,load:load,override:override,courseTitle:courseTitle,subjectTitle:subjectTitle,statusClass:statusClass,stat:stat,quizRate:quizRate},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.Bootstrap({}).then(function(r){var x=r.result||{};data.courses=x.courses||[];data.subjects=x.subjects||[];data.profiles=x.profiles||[];load();});}
 function subjectsForCourse(){return data.subjects.filter(function(x){return !data.filters.course_id||String(x.course_id)===String(data.filters.course_id);});}
 function courseChanged(){data.filters.subject_id='';data.filters.lesson_id='';data.lessons=[];load();}
 function subjectChanged(){data.filters.lesson_id='';if(!data.filters.subject_id){data.lessons=[];load();return;}api.services.ListLessons({subject_id:data.filters.subject_id}).then(function(r){data.lessons=r.result||[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});load();});}
 function load(){api.services.ProgressReport(clone(data.filters)).then(function(r){if(r.success){data.rows=r.result||[];data.rows.forEach(function(x){x.quiz_passed=truthy(x.quiz_passed);x.assignment_passed=truthy(x.assignment_passed);x.lesson_completed=truthy(x.lesson_completed);});}else fail('Progress report could not be loaded.');});api.services.ResultsReport(clone(data.filters)).then(function(r){if(r.success)data.results=r.result||[];else fail('Course results could not be loaded.');});api.services.ListQuizAttempts(clone(data.filters)).then(function(r){if(r.success)data.attempts=r.result||[];else fail('Quiz attempt metrics could not be loaded.');});}
 function override(x){api.services.OverrideLesson({lesson_id:x.lesson_id,student_id:x.student_id}).then(function(r){if(r.success){ok('Lesson lock overridden for '+x.student_name+'.');load();}else fail('Override could not be saved.');});}
 function stat(type){var n=0;data.rows.forEach(function(x){if(type==='completed'&&truthy(x.lesson_completed))n++;if(type==='quiz'&&truthy(x.quiz_passed))n++;if(type==='assignment'&&truthy(x.assignment_passed))n++;if(type==='inactive'&&!x.last_viewed_at)n++;});return n;}
 function quizRate(){if(!data.attempts.length)return 0;var passed=0;data.attempts.forEach(function(x){if(truthy(x.passed))passed++;});return Math.round((passed/data.attempts.length)*100);}
 function courseTitle(id){var t=id;data.courses.forEach(function(x){if(String(x.id)===String(id))t=x.code;});return t;}function subjectTitle(id){var t='';data.subjects.forEach(function(x){if(String(x.id)===String(id))t=x.code||x.title;});return t;}function statusClass(v){return'lm-badge '+String(v||'in_progress').toLowerCase();}function truthy(v){return v===true||v===1||v==='1'||v==='true';}function go(p){if(router&&router.appNavigate)router.appNavigate('/'+p);else location.hash='#/app/lesson-manager/'+p;}function clone(x){return JSON.parse(JSON.stringify(x||{}));}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
