WEBDOCK.component().register(function(exports){
 var api,router;var data={courses:[],subjects:[],assignments:[],lessons:[],content:[],videos:[],rules:[],courseId:'',subjectId:'',selected:null,tab:'lesson',errors:[],info:[],lessonForm:newLesson(),contentForm:newContent(),videoForm:newVideo(),ruleForm:newRule()};
 exports.vue={data:data,methods:{go:go,onCourseChange:onCourseChange,loadLessons:loadLessons,subjectsForCourse:subjectsForCourse,newLesson:clearLesson,selectLesson:selectLesson,saveLesson:saveLesson,removeLesson:removeLesson,move:move,setTab:setTab,saveContent:saveContent,editContent:editContent,removeContent:removeContent,saveVideo:saveVideo,editVideo:editVideo,removeVideo:removeVideo,saveRule:saveRule,editRule:editRule,courseTitle:courseTitle,subjectTitle:subjectTitle,statusClass:statusClass},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.Bootstrap({}).then(function(r){if(!r.success)return fail('Could not load Course Manager data.');var x=r.result||{};data.courses=x.courses||[];data.subjects=x.subjects||[];data.assignments=x.assignments||[];if(data.courses.length){data.courseId=data.courses[0].id;onCourseChange();}});}
 function newLesson(){return{subject_id:'',title:'',description:'',lesson_order:1,passing_mark:70,status:'draft',available_at:'',progression_enabled:true,require_reading:true,require_video:false,require_quiz:false,require_assignment:false,require_teacher_approval:false};}
 function newContent(){return{lesson_id:'',content_type:'article',title:'',body:'',url:'',file_name:'',sort_order:1,is_required:true,status:'published'};}
 function newVideo(){return{lesson_id:'',title:'',provider:'youtube',video_url:'',thumbnail_url:'',duration_seconds:0,transcript:'',caption_url:'',sort_order:1,is_required:true,status:'published'};}
 function newRule(){return{lesson_id:'',assignment_id:'',submission_type:'file_and_text',passing_mark:50,allowed_formats:'pdf,doc,docx,jpg,png,mp4,mp3,zip',max_file_size_mb:50,max_submissions:3,allow_resubmission:true,allow_late:true,requires_approval:true,assignment:{title:'',description:'',due_at:'',max_mark:100,late_penalty_per_day:0,status:'published'}};}
 function subjectsForCourse(){return data.subjects.filter(function(x){return String(x.course_id)===String(data.courseId);});}
 function onCourseChange(){var available=subjectsForCourse();data.subjectId=available.length?available[0].id:'';loadLessons();}
 function loadLessons(){data.selected=null;data.lessonForm=newLesson();data.lessonForm.subject_id=data.subjectId;if(!data.subjectId){data.lessons=[];return;}api.services.ListLessons({subject_id:data.subjectId}).then(function(r){data.lessons=r.success?(r.result||[]):[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});});}
 function clearLesson(){data.selected=null;data.lessonForm=newLesson();data.lessonForm.subject_id=data.subjectId;data.lessonForm.lesson_order=data.lessons.length+1;data.tab='lesson';}
 function selectLesson(x){data.selected=x;data.lessonForm=clone(x);data.courseId=x.course_id;data.subjectId=x.subject_id;data.tab='lesson';loadChildren(x.id);}
 function loadChildren(id){api.services.ListContent({lesson_id:id}).then(function(r){data.content=r.success?(r.result||[]):[];});api.services.ListVideos({lesson_id:id}).then(function(r){data.videos=r.success?(r.result||[]):[];});api.services.ListAssignmentRules({lesson_id:id}).then(function(r){data.rules=r.success?(r.result||[]):[];});data.contentForm=newContent();data.contentForm.lesson_id=id;data.videoForm=newVideo();data.videoForm.lesson_id=id;data.ruleForm=newRule();data.ruleForm.lesson_id=id;}
 function saveLesson(){data.lessonForm.subject_id=data.subjectId;delete data.lessonForm.course_id;api.services.SaveLesson(clone(data.lessonForm)).then(function(r){if(!r.success)return fail(message(r,'Lesson could not be saved.'));ok('Lesson saved under '+subjectTitle(data.subjectId)+'.');data.selected=r.result;data.lessonForm=clone(r.result);loadLessonsAndReselect(r.result.id);});}
 function loadLessonsAndReselect(id){api.services.ListLessons({subject_id:data.subjectId}).then(function(r){data.lessons=r.result||[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});data.lessons.forEach(function(x){if(String(x.id)===String(id)){data.selected=x;data.lessonForm=clone(x);loadChildren(x.id);}});});}
 function removeLesson(x){if(!confirm('Delete this lesson?'))return;api.services.DeleteLesson({id:x.id}).then(function(r){if(r.success){ok('Lesson deleted.');loadLessons();}else fail('Lesson could not be deleted.');});}
 function move(x,offset){var i=data.lessons.indexOf(x),j=i+offset;if(j<0||j>=data.lessons.length)return;var tmp=data.lessons[i];data.lessons.splice(i,1);data.lessons.splice(j,0,tmp);api.services.ReorderLessons({lessons:data.lessons}).then(function(r){if(r.success){ok('Lesson order updated.');loadLessonsAndReselect(x.id);}else fail('Order could not be updated.');});}
 function setTab(v){data.tab=v;}
 function saveContent(){data.contentForm.lesson_id=data.selected.id;api.services.SaveContent(clone(data.contentForm)).then(function(r){if(r.success){ok('Material saved.');loadChildren(data.selected.id);}else fail(message(r,'Material could not be saved.'));});}function editContent(x){data.contentForm=clone(x);data.tab='content';}function removeContent(x){api.services.DeleteContent({id:x.id}).then(function(r){if(r.success)loadChildren(data.selected.id);});}
 function saveVideo(){data.videoForm.lesson_id=data.selected.id;api.services.SaveVideo(clone(data.videoForm)).then(function(r){if(r.success){ok('Video saved.');loadChildren(data.selected.id);}else fail(message(r,'Video could not be saved.'));});}function editVideo(x){data.videoForm=clone(x);data.tab='video';}function removeVideo(x){api.services.DeleteVideo({id:x.id}).then(function(r){if(r.success)loadChildren(data.selected.id);});}
 function saveRule(){data.ruleForm.lesson_id=data.selected.id;if(data.ruleForm.assignment_id)delete data.ruleForm.assignment;api.services.SaveAssignmentRule(clone(data.ruleForm)).then(function(r){if(r.success){ok('Assignment linked to lesson.');loadChildren(data.selected.id);}else fail(message(r,'Assignment rule could not be saved.'));});}function editRule(x){data.ruleForm=clone(x);data.ruleForm.assignment={title:'',description:'',due_at:'',max_mark:100,status:'published'};data.tab='assignment';}
 function courseTitle(id){var t=id;data.courses.forEach(function(x){if(String(x.id)===String(id))t=x.code+' · '+x.title;});return t;}function subjectTitle(id){var t='';data.subjects.forEach(function(x){if(String(x.id)===String(id))t=x.code+' · '+x.title;});return t||'selected subject';}function statusClass(v){return'lm-badge '+String(v||'draft').toLowerCase();}function go(p){if(router&&router.appNavigate)router.appNavigate('../'+p);}function clone(x){return JSON.parse(JSON.stringify(x||{}));}function message(r,d){return r.result&&r.result.message?r.result.message:d;}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
