WEBDOCK.component().register(function(exports){
 var api,router,metadataTimer;var richEditorReady=false;var videoDirty={title:false,thumbnail_url:false,transcript:false};var data={courses:[],subjects:[],assignments:[],lessons:[],content:[],videos:[],rules:[],courseId:'',subjectId:'',selected:null,tab:'lesson',errors:[],info:[],metadataLoading:false,metadataMessages:[],lessonForm:newLesson(),contentForm:newContent(),videoForm:newVideo(),ruleForm:newRule()};
 exports.vue={data:data,methods:{go:go,onCourseChange:onCourseChange,loadLessons:loadLessons,subjectsForCourse:subjectsForCourse,newLesson:clearLesson,selectLesson:selectLesson,saveLesson:saveLesson,removeLesson:removeLesson,move:move,setTab:setTab,saveContent:saveContent,editContent:editContent,removeContent:removeContent,saveVideo:saveVideo,editVideo:editVideo,removeVideo:removeVideo,saveRule:saveRule,editRule:editRule,courseTitle:courseTitle,subjectTitle:subjectTitle,statusClass:statusClass,richCommand:richCommand,syncRichText:syncRichText,scheduleMetadata:scheduleMetadata,fetchVideoMetadata:fetchVideoMetadata,markVideoField:markVideoField,onProviderChange:onProviderChange},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.Bootstrap({}).then(function(r){if(!r.success)return fail('Could not load Course Manager data.');var x=r.result||{};data.courses=x.courses||[];data.subjects=x.subjects||[];data.assignments=x.assignments||[];if(data.courses.length){data.courseId=data.courses[0].id;onCourseChange();}});}
 function newLesson(){return{subject_id:'',title:'',description:'',lesson_order:1,passing_mark:70,status:'draft',available_at:'',progression_enabled:true,require_reading:true,require_video:false,require_quiz:false,require_assignment:false,require_teacher_approval:false};}
 function newContent(){return{lesson_id:'',content_type:'article',title:'',body:'',url:'',file_name:'',sort_order:1,is_required:true,status:'published'};}
 function newVideo(){return{lesson_id:'',title:'',provider:'youtube',video_url:'',thumbnail_url:'',duration_seconds:0,transcript:'',caption_url:'',sort_order:1,is_required:true,status:'published'};}
 function newRule(){return{lesson_id:'',assignment_id:'',submission_type:'file_and_text',passing_mark:50,allowed_formats:'pdf,doc,docx,jpg,png,mp4,mp3,zip',max_file_size_mb:50,max_submissions:3,allow_resubmission:true,allow_late:true,requires_approval:true,assignment:{title:'',description:'',due_at:'',max_mark:100,late_penalty_per_day:0,status:'published'}};}
 function subjectsForCourse(){return data.subjects.filter(function(x){return String(x.course_id)===String(data.courseId);});}
 function onCourseChange(){var available=subjectsForCourse();data.subjectId=available.length?available[0].id:'';loadLessons();}
 function loadLessons(){data.selected=null;data.lessonForm=newLesson();data.lessonForm.subject_id=data.subjectId;if(!data.subjectId){data.lessons=[];return;}api.services.ListLessons({subject_id:data.subjectId}).then(function(r){data.lessons=r.success?(r.result||[]):[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});});}
 function clearLesson(){data.selected=null;data.lessonForm=newLesson();data.lessonForm.subject_id=data.subjectId;data.lessonForm.lesson_order=data.lessons.length+1;data.tab='lesson';}
 function selectLesson(x){data.selected=x;data.lessonForm=clone(x);data.courseId=x.course_id;data.subjectId=x.subject_id;data.tab='lesson';loadChildren(x.id);}
 function loadChildren(id){api.services.ListContent({lesson_id:id}).then(function(r){data.content=r.success?(r.result||[]):[];});api.services.ListVideos({lesson_id:id}).then(function(r){data.videos=r.success?(r.result||[]):[];});api.services.ListAssignmentRules({lesson_id:id}).then(function(r){data.rules=r.success?(r.result||[]):[];});data.contentForm=newContent();data.contentForm.lesson_id=id;data.videoForm=newVideo();data.videoForm.lesson_id=id;videoDirty={title:false,thumbnail_url:false,transcript:false};data.metadataMessages=[];data.ruleForm=newRule();data.ruleForm.lesson_id=id;}
 function saveLesson(){data.lessonForm.subject_id=data.subjectId;delete data.lessonForm.course_id;api.services.SaveLesson(clone(data.lessonForm)).then(function(r){if(!r.success)return fail(message(r,'Lesson could not be saved.'));ok('Lesson saved under '+subjectTitle(data.subjectId)+'.');data.selected=r.result;data.lessonForm=clone(r.result);loadLessonsAndReselect(r.result.id);});}
 function loadLessonsAndReselect(id){api.services.ListLessons({subject_id:data.subjectId}).then(function(r){data.lessons=r.result||[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});data.lessons.forEach(function(x){if(String(x.id)===String(id)){data.selected=x;data.lessonForm=clone(x);loadChildren(x.id);}});});}
 function removeLesson(x){if(!confirm('Delete this lesson?'))return;api.services.DeleteLesson({id:x.id}).then(function(r){if(r.success){ok('Lesson deleted.');loadLessons();}else fail('Lesson could not be deleted.');});}
 function move(x,offset){var i=data.lessons.indexOf(x),j=i+offset;if(j<0||j>=data.lessons.length)return;var tmp=data.lessons[i];data.lessons.splice(i,1);data.lessons.splice(j,0,tmp);api.services.ReorderLessons({lessons:data.lessons}).then(function(r){if(r.success){ok('Lesson order updated.');loadLessonsAndReselect(x.id);}else fail('Order could not be updated.');});}
 function setTab(v){data.tab=v;if(v==='content')setTimeout(function(){initializeRichEditor(data.contentForm.body||'');},0);}
 function saveContent(){syncRichText();data.contentForm.lesson_id=data.selected.id;api.services.SaveContent(clone(data.contentForm)).then(function(r){if(r.success){ok('Material saved.');loadChildren(data.selected.id);setTimeout(function(){initializeRichEditor('');},0);}else fail(message(r,'Material could not be saved.'));});}function editContent(x){data.contentForm=clone(x);data.tab='content';setTimeout(function(){initializeRichEditor(data.contentForm.body||'');},0);}function removeContent(x){api.services.DeleteContent({id:x.id}).then(function(r){if(r.success)loadChildren(data.selected.id);});}
 function saveVideo(){if(data.metadataLoading)return;data.videoForm.lesson_id=data.selected.id;api.services.SaveVideo(clone(data.videoForm)).then(function(r){if(r.success){ok('Video saved.');loadChildren(data.selected.id);}else fail(message(r,'Video could not be saved.'));});}function editVideo(x){data.videoForm=clone(x);videoDirty={title:true,thumbnail_url:true,transcript:true};data.metadataMessages=[];data.tab='video';}function removeVideo(x){api.services.DeleteVideo({id:x.id}).then(function(r){if(r.success)loadChildren(data.selected.id);});}
 function saveRule(){data.ruleForm.lesson_id=data.selected.id;if(data.ruleForm.assignment_id)delete data.ruleForm.assignment;api.services.SaveAssignmentRule(clone(data.ruleForm)).then(function(r){if(r.success){ok('Assignment linked to lesson.');loadChildren(data.selected.id);}else fail(message(r,'Assignment rule could not be saved.'));});}function editRule(x){data.ruleForm=clone(x);data.ruleForm.assignment={title:'',description:'',due_at:'',max_mark:100,status:'published'};data.tab='assignment';}
 function initializeRichEditor(value){var editor=document.getElementById('lessonRichTextEditor');if(!editor)return;richEditorReady=true;editor.innerHTML=value||'';syncRichText();}
 function syncRichText(){var editor=document.getElementById('lessonRichTextEditor');if(editor&&richEditorReady)data.contentForm.body=editor.innerHTML;}
 function richCommand(command,value){var editor=document.getElementById('lessonRichTextEditor');if(!editor)return;editor.focus();if(command==='createLink'){value=window.prompt('Link URL','https://');if(!value)return;}if(command==='insertImage'){value=window.prompt('Image URL','https://');if(!value)return;}document.execCommand(command,false,value||null);syncRichText();}
 function markVideoField(field){videoDirty[field]=true;}
 function onProviderChange(){data.metadataMessages=[];if(data.videoForm.video_url)scheduleMetadata();}
 function scheduleMetadata(){if(metadataTimer)clearTimeout(metadataTimer);if(['youtube','facebook'].indexOf(String(data.videoForm.provider).toLowerCase())<0||!data.videoForm.video_url)return;metadataTimer=setTimeout(function(){fetchVideoMetadata(false);},800);}
 function fetchVideoMetadata(force){if(data.metadataLoading)return;var provider=String(data.videoForm.provider||'').toLowerCase(),url=String(data.videoForm.video_url||'').trim();if(['youtube','facebook'].indexOf(provider)<0)return fail('Automatic metadata is available for YouTube and Facebook only.');if(!url)return fail('Enter a video URL first.');if(force&&(videoDirty.title||videoDirty.thumbnail_url||videoDirty.transcript)&&!confirm('Refresh metadata and replace fields you have edited where provider data is available?'))return;data.metadataLoading=true;data.metadataMessages=[];api.services.FetchVideoMetadata({provider:provider,video_url:url}).then(function(r){data.metadataLoading=false;if(!r.success)return fail(message(r,'Video metadata could not be fetched.'));var x=r.result||{};if(x.title&&(force||!videoDirty.title||!data.videoForm.title))data.videoForm.title=x.title;if(x.thumbnail_url&&(force||!videoDirty.thumbnail_url||!data.videoForm.thumbnail_url))data.videoForm.thumbnail_url=x.thumbnail_url;if(x.transcript&&(force||!videoDirty.transcript||!data.videoForm.transcript))data.videoForm.transcript=x.transcript;if(x.duration_seconds&&(!data.videoForm.duration_seconds||force))data.videoForm.duration_seconds=x.duration_seconds;data.metadataMessages=x.messages||[];ok('Available '+(provider==='youtube'?'YouTube':'Facebook')+' metadata loaded. Review it before saving.');}).error(function(){data.metadataLoading=false;fail('Video metadata could not be fetched.');});}
 function courseTitle(id){var t=id;data.courses.forEach(function(x){if(String(x.id)===String(id))t=x.code+' · '+x.title;});return t;}function subjectTitle(id){var t='';data.subjects.forEach(function(x){if(String(x.id)===String(id))t=x.code+' · '+x.title;});return t||'selected subject';}function statusClass(v){return'lm-badge '+String(v||'draft').toLowerCase();}function go(p){if(router&&router.appNavigate)router.appNavigate('../'+p);}function clone(x){return JSON.parse(JSON.stringify(x||{}));}function message(r,d){return r.result&&r.result.message?r.result.message:d;}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
