<?php
define("PLUGIN_PATH_LOCAL", dirname(__DIR__, 3) . "/plugins");

require_once dirname(__DIR__) . "/services/growth-workbench/service.php";
require_once dirname(__DIR__) . "/services/youtube-auth/service.php";

$contracts = array(
    "youtube_growth_agent\\GrowthWorkbenchService" => "postDownloadTranscript",
    "youtube_growth_agent\\YouTubeAuthService" => "postStartCaptionConnect"
);
foreach ($contracts as $class => $method) {
    $reflection = new ReflectionClass($class);
    if (!$reflection->hasMethod($method) || !$reflection->getMethod($method)->isPublic()) {
        fwrite(STDERR, "FAIL: missing public service contract " . $class . "::" . $method . PHP_EOL);
        exit(1);
    }
}

$serviceReflection = new ReflectionClass("youtube_growth_agent\\GrowthWorkbenchService");
$service = $serviceReflection->newInstanceWithoutConstructor();
$scopeMethod = $serviceReflection->getMethod("hasCaptionScope");
$scopeMethod->setAccessible(true);
if (!$scopeMethod->invoke($service, (object)array("scopes" => json_encode(array("https://www.googleapis.com/auth/youtube.force-ssl"))))) {
    fwrite(STDERR, "FAIL: serialized caption scope should be recognized" . PHP_EOL);
    exit(1);
}
if ($scopeMethod->invoke($service, (object)array("scopes" => array("https://www.googleapis.com/auth/youtube.readonly")))) {
    fwrite(STDERR, "FAIL: read-only scope must not enable caption downloads" . PHP_EOL);
    exit(1);
}

$trackMethod = $serviceReflection->getMethod("selectCaptionTrack");
$trackMethod->setAccessible(true);
$track = $trackMethod->invoke($service, array(
    array("id" => "failed", "snippet" => array("language" => "en", "status" => "failed", "trackKind" => "standard")),
    array("id" => "auto-en", "snippet" => array("language" => "en", "status" => "serving", "trackKind" => "asr")),
    array("id" => "manual-si", "snippet" => array("language" => "si", "status" => "serving", "trackKind" => "standard"))
), "si");
if ($track === null || $track->id !== "manual-si" || $track->autoGenerated) {
    fwrite(STDERR, "FAIL: preferred serving manual track should be selected" . PHP_EOL);
    exit(1);
}

echo "TRANSCRIPT_SERVICE_CONTRACTS_OK" . PHP_EOL;
?>
