WEBDOCK.component().register(function(exports){
 var api,router;var data={courses:[],courseId:'',course:null,lessons:[],current:null,quiz:null,quizQuestions:[],answers:{},quizResult:null,assignmentForm:{content:'',file_url:''},errors:[],info:[],loading:false};
 exports.vue={data:data,methods:{go:go,loadCourse:loadCourse,openLesson:openLesson,previous:previous,next:next,markReading:markReading,markVideo:markVideo,startQuiz:startQuiz,submitQuiz:submitQuiz,submitAssignment:submitAssignment,options:options,toggleAnswer:toggleAnswer,isSelected:isSelected,videoEmbed:videoEmbed,isEmbeddable:isEmbeddable,statusClass:statusClass,courseProgress:courseProgress},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.StudentCourses({}).then(function(r){if(!r.success)return fail(msg(r,'Assigned courses could not be loaded.'));data.courses=r.result||[];if(data.courses.length){data.courseId=data.courses[0].id;loadCourse();}}).error(function(){fail('Assigned courses could not be loaded.');});}
 function resetLessonState(){data.current=null;data.quiz=null;data.quizQuestions=[];data.quizResult=null;data.answers={};data.assignmentForm={content:'',file_url:''};}
 function loadCourse(){if(!data.courseId)return;data.loading=true;data.course=null;data.lessons=[];resetLessonState();api.services.LearningCourse({course_id:data.courseId}).then(function(r){data.loading=false;if(!r.success)return fail(msg(r,'Course could not be opened.'));var x=r.result||{};data.course=x.course;data.lessons=x.lessons||[];data.lessons.forEach(normalizeLesson);var first=null;data.lessons.forEach(function(l){if(!first&&l.unlocked&&!(l.progress&&l.progress.lesson_completed))first=l;});if(!first)data.lessons.forEach(function(l){if(!first&&l.unlocked)first=l;});if(first)openLesson(first);else if(!data.lessons.length)ok('This assigned course has no published lessons yet.');}).error(function(){data.loading=false;fail('Course could not be opened.');});}
 function openLesson(l){if(!l||!l.unlocked)return;data.current=l;data.quiz=null;data.quizQuestions=[];data.quizResult=null;data.answers={};data.assignmentForm={content:'',file_url:''};api.services.StartLesson({lesson_id:l.id}).then(function(r){if(r.success)l.progress=r.result;});}
 function currentIndex(){return data.lessons.indexOf(data.current);}function previous(){var i=currentIndex();if(i>0&&data.lessons[i-1].unlocked)openLesson(data.lessons[i-1]);}function next(){var i=currentIndex();if(i>=0&&i<data.lessons.length-1&&data.lessons[i+1].unlocked)openLesson(data.lessons[i+1]);}
 function markReading(){complete('reading','Reading marked complete.');}function markVideo(){complete('video','Video marked complete.');}function complete(activity,text){api.services.CompleteActivity({lesson_id:data.current.id,activity:activity}).then(function(r){if(r.success){data.current.progress=r.result;ok(text);refreshCurrent();}else fail(msg(r,'Progress could not be saved.'));});}
 function refreshCurrent(){var id=data.current.id;api.services.LearningCourse({course_id:data.courseId}).then(function(r){if(!r.success)return;data.lessons=r.result.lessons||[];data.lessons.forEach(normalizeLesson);data.lessons.forEach(function(x){if(String(x.id)===String(id))data.current=x;});});}
 function startQuiz(q){data.quiz=q;data.answers={};data.quizResult=null;api.services.ListQuestions({quiz_id:q.id}).then(function(r){data.quizQuestions=r.result||[];data.quizQuestions.forEach(function(x){data.answers[String(x.id)]=x.question_type==='multiple_answer'?[]:'';});});}
 function submitQuiz(){api.services.SubmitQuiz({quiz_id:data.quiz.id,answers:data.answers,started_at:new Date().toISOString()}).then(function(r){if(!r.success)return fail(msg(r,'Quiz could not be submitted.'));data.quizResult=r.result;ok(r.result.passed?'Quiz passed. The next requirement is available.':'Attempt saved. Review the result and retry if allowed.');refreshCurrent();});}
 function submitAssignment(rule){api.services.SubmitAssignment({lesson_id:data.current.id,assignment_id:rule.assignment_id,content:data.assignmentForm.content,file_url:data.assignmentForm.file_url}).then(function(r){if(r.success){ok('Assignment submitted for teacher review.');data.assignmentForm={content:'',file_url:''};refreshCurrent();}else fail(msg(r,'Assignment could not be submitted.'));});}
 function toggleAnswer(q,o){var key=String(q.id),arr=data.answers[key]||[],i=arr.indexOf(o);if(i>=0)arr.splice(i,1);else arr.push(o);data.answers[key]=arr;}function isSelected(q,o){return(data.answers[String(q.id)]||[]).indexOf(o)>=0;}function options(q){return Array.isArray(q.options)?q.options:String(q.options||'').split(',');}
 function isEmbeddable(v){return['youtube','cloudflare'].indexOf(String(v.provider).toLowerCase())>=0;}function videoEmbed(v){var u=String(v.video_url||'');if(String(v.provider).toLowerCase()==='youtube'){var id='';if(u.indexOf('youtu.be/')>=0)id=u.split('youtu.be/')[1].split(/[?&]/)[0];else if(u.indexOf('v=')>=0)id=u.split('v=')[1].split('&')[0];else if(u.indexOf('/embed/')>=0)id=u.split('/embed/')[1].split(/[?&]/)[0];return'https://www.youtube.com/embed/'+id;}return u;}
 function normalizeLesson(l){['require_reading','require_video','require_quiz','require_assignment','require_teacher_approval','progression_enabled'].forEach(function(k){l[k]=truthy(l[k]);});if(l.progress)['lesson_completed','reading_completed','video_completed','quiz_completed','quiz_passed','assignment_submitted','assignment_passed','teacher_approved','override_unlocked'].forEach(function(k){l.progress[k]=truthy(l.progress[k]);});}function courseProgress(){var value=0;data.courses.forEach(function(c){if(String(c.id)===String(data.courseId))value=c.completion_percentage||0;});return value;}function statusClass(v){return'lm-badge '+String(v||'locked').toLowerCase();}function go(p){if(router&&router.appNavigate)router.appNavigate('../'+p);}function truthy(v){return v===true||v===1||v==='1'||v==='true';}function msg(r,d){return r.result&&r.result.message?r.result.message:d;}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
