<?php
namespace davvag_credit_points;
require_once __DIR__ . "/CreditLedgerService.php";
class CreditRewardService {
    private $ledger;
    public function __construct($ledger=null){$this->ledger=$ledger?:new CreditLedgerService();}
    public function status($profileId){$db=$this->ledger->database();$rules=$db->all("SELECT r.*,p.code program_code FROM davvag_credit_reward_rule r JOIN davvag_credit_program p ON p.id=r.program_id WHERE r.status='ACTIVE' AND (r.active_from IS NULL OR r.active_from<=NOW()) AND (r.active_until IS NULL OR r.active_until>=NOW()) ORDER BY r.id");foreach($rules as$rule){$rule->period_key=CreditRules::periodKey($rule->cadence,$rule->timezone);$claim=$db->one("SELECT * FROM davvag_credit_reward_claim WHERE rule_id=? AND profile_id=? AND period_key=? LIMIT 1","iis",array($rule->id,intval($profileId),$rule->period_key));$rule->claimed=$claim!==null;$rule->claim=$claim;}return$rules;}
    public function claim($profileId,$ruleId,$idempotencyKey,$actor=array()){$db=$this->ledger->database();$rule=$db->one("SELECT r.*,p.code program_code,p.reward_available FROM davvag_credit_reward_rule r JOIN davvag_credit_program p ON p.id=r.program_id WHERE r.id=? LIMIT 1","i",array(intval($ruleId)));if(!$rule||strtoupper($rule->status)!=="ACTIVE"||!CreditRules::truthy($rule->reward_available))throw new CreditException("Reward is unavailable.");$now=time();if(!empty($rule->active_from)&&strtotime($rule->active_from)>$now||!empty($rule->active_until)&&strtotime($rule->active_until)<$now)throw new CreditException("Reward is unavailable.");$period=CreditRules::periodKey($rule->cadence,$rule->timezone);$existing=$db->one("SELECT * FROM davvag_credit_reward_claim WHERE rule_id=? AND profile_id=? AND period_key=? LIMIT 1","iis",array($rule->id,intval($profileId),$period));if($existing)throw new CreditException("This reward has already been claimed for the current period.");$expires=null;if(intval($rule->expiry_days)>0)$expires=date("Y-m-d H:i:s",time()+intval($rule->expiry_days)*86400);$context=array("programCode"=>$rule->program_code,"sourceApp"=>"davvag-credit-points","referenceType"=>"reward-claim","referenceId"=>$rule->id.":".$profileId.":".$period,"idempotencyKey"=>CreditRules::idempotency($idempotencyKey),"description"=>"Claim ".$rule->title,"metadata"=>array("ruleId"=>intval($rule->id),"periodKey"=>$period),"actorProfileId"=>intval(isset($actor["profileId"])?$actor["profileId"]:$profileId),"actorUserId"=>isset($actor["userId"])?$actor["userId"]:"");return$this->ledger->credit($profileId,$rule->credit_amount,$context,strtoupper($rule->cadence)."_REWARD",$expires,false,function($txdb,$tx)use($rule,$profileId,$period,$idempotencyKey){$txdb->insert("davvag_credit_reward_claim",array("rule_id"=>intval($rule->id),"profile_id"=>intval($profileId),"period_key"=>$period,"claim_status"=>"CLAIMED","idempotency_key"=>$idempotencyKey,"transaction_id"=>intval($tx->id),"claimed_at"=>date("Y-m-d H:i:s")));});}
}
?>
