<?php
// Included by the isolated integration runner; uses only its freshly created database.
require_once TENANT_RESOURCE_LOCATION.'/apps/lesson-manager/services/api/service.php';
require_once TENANT_RESOURCE_LOCATION.'/apps/course-manager/services/api/service.php';
require_once dirname(__DIR__).'/services/marketplace-api/service.php';
require_once TENANT_RESOURCE_LOCATION.'/apps/davvag-credit-points/lib/CreditCheckoutService.php';
class EndpointRequest {private $data;function __construct($data){$this->data=(object)$data;}function Body($decode=true){return $this->data;}}
class EndpointResponse {public $error=null;function SetError($error){$this->error=$error;}function GetError(){return $this->error;}}
function endpoint($class,$method,$body=[]){$response=new EndpointResponse();$value=(new $class())->$method(new EndpointRequest($body),$response);return [$value,$response->error];}
$market='lesson_market_place\\MarketplaceApi';$lessonApi='lesson_manager\\ApiService';
[$boundary,$bv,$boundaryTerms]=$make(0,false);$engine->request(3,$boundary,$bv,'boundary-free-request');
Auth::$role='web_user';Profile::$id=3;
$courseDescriptor=json_decode(file_get_contents(TENANT_RESOURCE_LOCATION.'/apps/course-manager/services/api/component.json'));
$roster=SOSSData::WithServiceNamespaces($courseDescriptor->serviceHandler->serviceNamespaces,function()use($cohort,$subject){return endpoint('course_manager\\ApiService','postAttendanceRoster',['class_grade_id'=>$cohort,'subject_id'=>$subject]);});
check(!$roster[1] && count($roster[0]->students)===2 && in_array(3,array_map(function($student){return (int)$student->student_id;},$roster[0]->students),true),'Course Manager attendance roster includes activated marketplace learner');
foreach(['lesson_manager_content','lesson_manager_quiz','lesson_manager_question','lesson_manager_progress','course_manager_assignment','course_manager_submission'] as $ns)SOSSData::WithServiceNamespaces([$ns],function()use($ns){SOSSData::Query($ns,'',null,'asc',1,0,null,false);});
$db->updateById('lesson_manager_lesson',1,['require_reading'=>'true']);
$db->updateById('lesson_manager_lesson',3,['is_free'=>'true']);
foreach([1,3] as $id){$db->insert('lesson_manager_content',['lesson_id'=>$id,'title'=>'Protected '.$id,'content_type'=>'html','body'=>json_encode('<p>Secret '.$id.'</p>'),'url'=>'components/dock/soss-uploader/service/get/lesson_content_resource/secret'.$id.'.pdf','status'=>'published']);$db->insert('lesson_manager_quiz',['id'=>$id,'lesson_id'=>$id,'title'=>'Quiz '.$id,'status'=>'published']);$db->insert('lesson_manager_question',['quiz_id'=>$id,'question_text'=>'Question','question_type'=>'true_false','correct_answer'=>'true','status'=>'active']);}
[$learning,$error]=endpoint($lessonApi,'postLearningCourse',['course_id'=>$course,'student_id'=>1]);check(!$error && count($learning['lessons'])===2 && $learning['student']->id===3,'LearningCourse isolates package lessons and ignores learner impersonation');
[$courses,$error]=endpoint($lessonApi,'postStudentCourses');check(!$error && count($courses)===1,'package-only learner discovers course through actual API');
foreach([['postStartLesson',['lesson_id'=>3]],['postCompleteActivity',['lesson_id'=>3,'activity'=>'reading']],['postStartQuiz',['quiz_id'=>3]],['postListQuestions',['quiz_id'=>3]],['postSubmitQuiz',['quiz_id'=>3,'answers'=>[]]],['postSubmitAssignment',['lesson_id'=>3,'assignment_id'=>1]],['postProgressReport',[]],['postSubmissionsReport',[]],['postListQuizAttempts',[]],['postResultsReport',[]]] as [$method,$body]){[$value,$error]=endpoint($lessonApi,$method,$body);check($error!==null,$method.' denies unrelated content or staff reports');}
$balanceBefore=$ledger->summary(3)->availableBalance;[$opened,$error]=endpoint($lessonApi,'postStartLesson',['lesson_id'=>1]);check(!$error && $opened,'included paid lesson opens through actual API');check($ledger->summary(3)->availableBalance===$balanceBefore,'opening package lesson creates no extra debit');
[$blocked,$error]=endpoint($lessonApi,'postStartLesson',['lesson_id'=>2]);check($error!==null,'package grant retains required progression');
[$questions,$error]=endpoint($lessonApi,'postListQuestions',['quiz_id'=>1]);check(!$error && count($questions)===1 && !isset($questions[0]->correct_answer),'included quiz metadata omits answers');
[$progress,$error]=endpoint($lessonApi,'postCompleteActivity',['lesson_id'=>1,'activity'=>'reading']);check(!$error && $progress,'included activity writes own progress');
check(!(new \lesson_manager\ApiService())->canReadMedia('lesson_content_resource','secret3.pdf',3),'unrelated resource denied by shared API resolver');
check((new \lesson_manager\ApiService())->canReadMedia('lesson_content_resource','secret1.pdf',3),'included resource allowed');
[$wrong,$error]=endpoint($market,'postRequestEnrolment',['package_id'=>$boundary,'version_id'=>$bv,'operation_key'=>'tampered-request','profile_id'=>1,'credit_price'=>0]);check($error!==null,'marketplace rejects tampered identity and price fields');
Auth::$role='teacher';Profile::$id=98;[$wrong,$error]=endpoint($market,'postAdminPackage',['id'=>$boundary]);check($error!==null,'teacher role cannot manage unrelated package');
Auth::$role='anonymous';Profile::$id=3;[$public,$error]=endpoint($market,'postPackage',['slug'=>$boundaryTerms->slug]);check(!$error && !$public['signed_in'] && !$public['attempt'] && !isset($public['terms']->lessons[0]->body),'anonymous package is metadata only despite a profile');
[$wrong,$error]=endpoint($market,'postRequestEnrolment',['package_id'=>$boundary,'version_id'=>$bv,'operation_key'=>'anonymous-request']);check($error!==null,'anonymous enrolment denied');
$db->updateById('lmp_package',$boundary,['status'=>'unpublished']);[$wrong,$error]=endpoint($market,'postPackage',['slug'=>$boundaryTerms->slug]);check($error!==null,'unpublished package hidden from anonymous');
Auth::$role='sysadmin';Profile::$id=1;
[$immutable,$iv]=$make(10,true);$recorded=$engine->request(4,$immutable,$iv,'immutable-request');$changed=$db->one('SELECT * FROM lmp_version WHERE id=?','i',[$iv]);$newTerms=json_decode($changed->snapshot_json);$newTerms->credit_price=50;$newId=$db->insert('lmp_version',['package_id'=>$immutable,'version_number'=>2,'snapshot_json'=>json_encode($newTerms),'snapshot_hash'=>hash('sha256',json_encode($newTerms))]);$db->updateById('lmp_package',$immutable,['published_version_id'=>$newId]);$engine->decide(99,$recorded->id,'approve','','',function(){});$ledger->credit(4,10,['sourceApp'=>'test','referenceType'=>'fixture','referenceId'=>'immutable','idempotencyKey'=>'immutable-funds','description'=>'Fixture']);$settled=$engine->confirm(4,$recorded->id,$iv);check($settled->terms->credit_price===10 && $ledger->summary(4)->availableBalance===0,'pending recorded version settles at agreed price after publication changes');

// Real checkout service and real ledger, with transport fixtures at the provider HTTP boundary.
putenv('DAVVAG_CREDIT_CHECKOUT_BASE_URL=http://localhost/davvag-core');
$payment=new \davvag_credit_points\CreditPaymentService($ledger);$program=$ledger->program();
$topup=$db->insert('davvag_credit_package',['program_id'=>(int)$program->id,'package_code'=>'CHECKOUT','title'=>'Fixture credits','credit_amount'=>20,'bonus_credit_amount'=>5,'price_minor'=>100,'currency'=>'LKR','payment_channel'=>'STRIPE','status'=>'ACTIVE']);
$sessions=[];$calls=[];$transport=function($method,$path,$fields,$key)use(&$sessions,&$calls){$calls[]=[$method,$path,$fields,$key];if($method==='POST'){$id='cs_test_Fixture'.$fields['metadata']['credit_order_id'];$session=(object)['id'=>$id,'url'=>'https://checkout.stripe.com/c/pay/'.$id,'mode'=>'payment','client_reference_id'=>$fields['client_reference_id'],'metadata'=>(object)$fields['metadata'],'amount_total'=>$fields['line_items'][0]['price_data']['unit_amount'],'currency'=>$fields['line_items'][0]['price_data']['currency'],'status'=>'open','payment_status'=>'unpaid'];return $sessions[$id]=$session;}return clone $sessions[basename($path)];};
$provider=new \davvag_stripe\CreditCheckoutAdapter($transport);$checkout=new \davvag_credit_points\CreditCheckoutService($ledger,$provider);
$order=$payment->createOrder(5,$topup,'checkout-order');$return='#/app/lesson-market-place/package?slug=package-1';$started=$checkout->start(5,$order->id,$return);check(strpos($started['checkout_url'],'https://checkout.stripe.com/')===0 && $calls[0][2]['line_items'][0]['price_data']['unit_amount']===100,'checkout creates provider session from stored price');
check($checkout->start(5,$order->id,$return)===$started && count($calls)===1,'checkout initiation replay reuses stored session');rejects(function()use($checkout,$order,$return){$checkout->start(6,$order->id,$return);},'checkout ownership enforced');rejects(function()use($checkout,$order){$checkout->start(5,$order->id,'https://evil.example');},'external return rejected');
$pending=$checkout->reconcile($order->id,5);check($pending->order_status==='PAYMENT_PENDING' && $ledger->summary(5)->availableBalance===0,'cancel/browser return with unpaid session credits nothing');
$session=$sessions['cs_test_Fixture'.$order->id];$session->status='complete';$session->payment_status='paid';
foreach(['amount_total'=>101,'currency'=>'USD','client_reference_id'=>'foreign','mode'=>'subscription'] as $field=>$bad){$old=$session->$field;$session->$field=$bad;rejects(function()use($checkout,$order){$checkout->reconcile($order->id,5);},'mismatched provider '.$field.' rejected');$session->$field=$old;}
$oldTenant=$session->metadata->tenant;$session->metadata->tenant='foreign';rejects(function()use($checkout,$order){$checkout->reconcile($order->id,5);},'provider tenant mismatch denied');$session->metadata->tenant=$oldTenant;
$admin->query("CREATE TRIGGER checkout_failure BEFORE INSERT ON davvag_credit_payment_event FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='injected checkout failure'");rejects(function()use($checkout,$order){$checkout->reconcile($order->id,5);},'settlement failure rolls back credit');$admin->query('DROP TRIGGER checkout_failure');check($ledger->summary(5)->availableBalance===0,'payment event failure leaves no wallet credit');
$paidOrder=$checkout->reconcile($order->id,5);check($paidOrder->order_status==='CREDITED' && $paidOrder->return_to===$return && $ledger->summary(5)->availableBalance===25,'verified payment credits base and bonus and preserves return');$checkout->reconcile($order->id,5);check($ledger->summary(5)->availableBalance===25,'settlement retry credits exactly once');
$expired=$payment->createOrder(5,$topup,'checkout-expired');$checkout->start(5,$expired->id,$return);$sessions['cs_test_Fixture'.$expired->id]->status='expired';$expiredState=$checkout->reconcile($expired->id,5);check($expiredState->provider_status==='EXPIRED' && $ledger->summary(5)->availableBalance===25,'expired checkout grants no additional credits');
$admin->query('ALTER TABLE lmp_audit DROP COLUMN reason');\lesson_market_place\MarketplaceSchema::ensure($db);\lesson_market_place\MarketplaceSchema::ensure($db);check((bool)$db->one("SELECT COLUMN_NAME FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='lmp_audit' AND column_name='reason'"),'repeatable migration restores missing nullable field without losing rows');

// CMS writes stay under this isolated test tenant, never the active site's pages.
define('GROUPID','sysadmin');Profile::$id=99;
$cmsSlug='lmp-fixture-'.substr(DATASTORE_DOMAIN,-16);
[$page,$error]=endpoint($market,'postPlaceOnPage',['id'=>$boundary,'page_slug'=>$cmsSlug,'page_title'=>'Fixture marketplace page']);check(!$error && $page['status']==='draft' && strpos($page['markup'],'webdock-app="lesson-market-place"')!==false,'staff creates draft CMS page through existing settings service');
[$repeat,$error]=endpoint($market,'postPlaceOnPage',['id'=>$boundary,'page_slug'=>$cmsSlug,'page_title'=>'Fixture marketplace page']);$storedPage=json_decode(file_get_contents(TENANT_RESOURCE_LOCATION.'/apps/davvag-cms-v7/content/pages/'.$cmsSlug.'.json'));check(!$error && count($storedPage->sections)===1,'repeated CMS placement does not duplicate package section');
