WEBDOCK.component().register(function(exports){
 var api,router;var data={courses:[],subjects:[],lessons:[],assignments:[],profiles:[],rows:[],filters:{course_id:'',subject_id:'',lesson_id:'',assignment_id:'',student_id:'',status:'',search:''},selected:null,reviewForm:{marks:0,feedback:'',status:'graded',approve:true},errors:[],info:[]};
 exports.vue={data:data,methods:{go:go,load:load,courseChanged:courseChanged,subjectChanged:subjectChanged,subjectsForCourse:subjectsForCourse,assignmentsForSubject:assignmentsForSubject,select:select,saveReview:saveReview,assignmentTitle:assignmentTitle,statusClass:statusClass},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.Bootstrap({}).then(function(r){var x=r.result||{};data.courses=x.courses||[];data.subjects=x.subjects||[];data.assignments=x.assignments||[];data.profiles=x.profiles||[];load();});}
 function subjectsForCourse(){return data.subjects.filter(function(x){return !data.filters.course_id||String(x.course_id)===String(data.filters.course_id);});}
 function assignmentsForSubject(){return data.assignments.filter(function(x){return !data.filters.subject_id||String(x.subject_id)===String(data.filters.subject_id);});}
 function courseChanged(){data.filters.subject_id='';data.filters.lesson_id='';data.filters.assignment_id='';data.lessons=[];load();}
 function subjectChanged(){data.filters.lesson_id='';data.filters.assignment_id='';if(!data.filters.subject_id){data.lessons=[];load();return;}api.services.ListLessons({subject_id:data.filters.subject_id}).then(function(r){data.lessons=r.result||[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});load();});}
 function load(){api.services.SubmissionsReport(clone(data.filters)).then(function(r){if(r.success)data.rows=r.result||[];else fail('Submissions could not be loaded.');});}
 function select(x){data.selected=x;data.reviewForm={marks:x.marks||0,feedback:x.feedback||'',status:x.status==='resubmission_requested'?'resubmission_requested':'graded',approve:true};}
 function saveReview(){if(!data.selected)return;var p=clone(data.reviewForm);p.submission_id=data.selected.id;api.services.ReviewSubmission(p).then(function(r){if(r.success){ok('Review saved and Course Manager gradebook updated.');data.selected=null;load();}else fail(msg(r,'Review could not be saved.'));});}
 function assignmentTitle(id){var t='Assignment #'+id;data.assignments.forEach(function(x){if(String(x.id)===String(id))t=x.title;});return t;}function statusClass(v){return'lm-badge '+String(v||'submitted').toLowerCase();}function go(p){if(router&&router.appNavigate)router.appNavigate('../'+p);}function clone(x){return JSON.parse(JSON.stringify(x||{}));}function msg(r,d){return r.result&&r.result.message?r.result.message:d;}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
