WEBDOCK.component().register(function(exports){
 var api,router;var data={courses:[],subjects:[],lessons:[],quizzes:[],questions:[],courseId:'',subjectId:'',lessonId:'',selectedQuiz:null,quizForm:newQuiz(),questionForm:newQuestion(),notes:'',questionCount:5,generating:false,preview:false,errors:[],info:[]};
 exports.vue={data:data,methods:{go:go,onCourseChange:onCourseChange,subjectsForCourse:subjectsForCourse,loadLessons:loadLessons,loadQuizzes:loadQuizzes,newQuiz:clearQuiz,selectQuiz:selectQuiz,saveQuiz:saveQuiz,generate:generate,editQuestion:editQuestion,saveQuestion:saveQuestion,removeQuestion:removeQuestion,newQuestion:clearQuestion,togglePreview:togglePreview,options:options,statusClass:statusClass},onReady:init};exports.onReady=function(){};
 function init(){api=exports.getComponent('api');router=exports.getShellComponent('soss-routes');api.services.Bootstrap({}).then(function(r){var x=r.result||{};data.courses=x.courses||[];data.subjects=x.subjects||[];if(data.courses.length){data.courseId=data.courses[0].id;onCourseChange();}});}
 function newQuiz(){return{lesson_id:'',title:'',instructions:'Answer every question.',passing_percentage:70,attempt_limit:3,time_limit_minutes:15,random_questions:true,random_answers:true,negative_marking:false,status:'draft'};}function newQuestion(){return{quiz_id:'',question_type:'multiple_choice',question_text:'',options_text:'',correct_text:'',explanation:'',difficulty:'medium',marks:1,negative_marks:0,sort_order:1,requires_manual_marking:false};}
 function subjectsForCourse(){return data.subjects.filter(function(x){return String(x.course_id)===String(data.courseId);});}
 function onCourseChange(){var available=subjectsForCourse();data.subjectId=available.length?available[0].id:'';loadLessons();}
 function loadLessons(){if(!data.subjectId){data.lessons=[];data.lessonId='';data.quizzes=[];return;}api.services.ListLessons({subject_id:data.subjectId}).then(function(r){data.lessons=r.result||[];data.lessons.sort(function(a,b){return Number(a.lesson_order)-Number(b.lesson_order);});if(data.lessons.length){data.lessonId=data.lessons[0].id;loadQuizzes();}else{data.lessonId='';data.quizzes=[];}});}
 function loadQuizzes(){data.selectedQuiz=null;data.questions=[];api.services.ListQuizzes({lesson_id:data.lessonId}).then(function(r){data.quizzes=r.result||[];});data.quizForm=newQuiz();data.quizForm.lesson_id=data.lessonId;}
 function clearQuiz(){data.selectedQuiz=null;data.questions=[];data.quizForm=newQuiz();data.quizForm.lesson_id=data.lessonId;data.preview=false;}
 function selectQuiz(x){data.selectedQuiz=x;data.quizForm=clone(x);data.preview=false;loadQuestions();}
 function loadQuestions(){api.services.ListQuestions({quiz_id:data.selectedQuiz.id}).then(function(r){data.questions=r.result||[];data.questionForm=newQuestion();data.questionForm.quiz_id=data.selectedQuiz.id;data.questionForm.sort_order=data.questions.length+1;});}
 function saveQuiz(){data.quizForm.lesson_id=data.lessonId;api.services.SaveQuiz(clone(data.quizForm)).then(function(r){if(!r.success)return fail(msg(r,'Quiz could not be saved.'));data.selectedQuiz=r.result;data.quizForm=clone(r.result);ok('Quiz saved.');loadQuizList(r.result.id);});}
 function loadQuizList(id){api.services.ListQuizzes({lesson_id:data.lessonId}).then(function(r){data.quizzes=r.result||[];data.quizzes.forEach(function(x){if(String(x.id)===String(id)){data.selectedQuiz=x;data.quizForm=clone(x);loadQuestions();}});});}
 function generate(){if(!data.lessonId)return fail('Select a lesson first.');data.generating=true;api.services.GenerateQuiz({lesson_id:data.lessonId,title:data.quizForm.title,passing_percentage:data.quizForm.passing_percentage,question_count:data.questionCount,notes:data.notes}).then(function(r){data.generating=false;if(!r.success)return fail(msg(r,'Quiz draft could not be generated.'));data.selectedQuiz=r.result.quiz;data.quizForm=clone(r.result.quiz);data.questions=r.result.questions||[];ok('Draft generated from lesson material. Review every answer before publishing.');loadQuizList(data.selectedQuiz.id);}).error(function(){data.generating=false;fail('Quiz draft could not be generated.');});}
 function editQuestion(q){data.questionForm=clone(q);data.questionForm.options_text=Array.isArray(q.options)?q.options.join('\n'):String(q.options||'');data.questionForm.correct_text=Array.isArray(q.correct_answer)?q.correct_answer.join('\n'):String(q.correct_answer||'');}
 function clearQuestion(){data.questionForm=newQuestion();data.questionForm.quiz_id=data.selectedQuiz?data.selectedQuiz.id:'';data.questionForm.sort_order=data.questions.length+1;}
 function saveQuestion(){if(!data.selectedQuiz)return fail('Save or select a quiz first.');var x=clone(data.questionForm);x.quiz_id=data.selectedQuiz.id;x.options=split(x.options_text);x.correct_answer=x.question_type==='multiple_answer'?split(x.correct_text):x.correct_text;delete x.options_text;delete x.correct_text;if(x.question_type==='short_answer')x.requires_manual_marking=true;api.services.SaveQuestion(x).then(function(r){if(r.success){ok('Question saved.');loadQuestions();}else fail(msg(r,'Question could not be saved.'));});}
 function removeQuestion(x){api.services.DeleteQuestion({id:x.id}).then(function(r){if(r.success)loadQuestions();});}function togglePreview(){data.preview=!data.preview;}function options(q){return Array.isArray(q.options)?q.options:split(String(q.options||''));}function split(v){return String(v||'').split(/\r?\n|,/).map(function(x){return x.trim();}).filter(function(x){return x;});}function statusClass(v){return'lm-badge '+String(v||'draft').toLowerCase();}function go(p){if(router&&router.appNavigate)router.appNavigate('../'+p);}function clone(x){return JSON.parse(JSON.stringify(x||{}));}function msg(r,d){return r.result&&r.result.message?r.result.message:d;}function fail(x){data.errors=[x];data.info=[];}function ok(x){data.info=[x];data.errors=[];}
});
