<?php
namespace davvag_credit_points;
require_once dirname(__DIR__,2)."/lib/CreditServiceSupport.php";
require_once dirname(__DIR__,2)."/lib/CreditCouponService.php";
require_once dirname(__DIR__,2)."/lib/CreditCurrencyAdapter.php";
class CreditAdminApiService {
    private function call($res,$fn){try{CreditServiceSupport::requireAdmin();return$fn();}catch(\Throwable$e){return CreditServiceSupport::fail($res,$e);}}
    private function body($req){return CreditServiceSupport::body($req);}
    private function save($table,$body,$fields){$db=(new CreditLedgerService())->database();$data=array();foreach($fields as$field)if(isset($body->{$field}))$data[$field]=$body->{$field};if(!$data)throw new CreditException("No supported fields were supplied.");if(isset($body->id)&&intval($body->id)>0){$db->updateById($table,intval($body->id),$data);return$db->one("SELECT * FROM `".$table."` WHERE id=?","i",array(intval($body->id)));}$id=$db->insert($table,$data);return$db->one("SELECT * FROM `".$table."` WHERE id=?","i",array($id));}
    public function postBootstrap($req,$res){return$this->call($res,function(){$l=new CreditLedgerService();$db=$l->database();$currency=new CreditCurrencyAdapter();return array("programs"=>$db->all("SELECT * FROM davvag_credit_program ORDER BY id"),"packages"=>$db->all("SELECT * FROM davvag_credit_package ORDER BY sort_order,id"),"rewards"=>$db->all("SELECT * FROM davvag_credit_reward_rule ORDER BY id"),"campaigns"=>$db->all("SELECT * FROM davvag_credit_coupon_campaign ORDER BY id"),"wallets"=>$db->all("SELECT * FROM davvag_credit_wallet WHERE wallet_type='USER_WALLET' ORDER BY id DESC LIMIT 100"),"currencies"=>$currency->active(),"defaultCurrency"=>$currency->defaultCurrency());});}
    public function postSaveProgram($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);if(isset($b->precision)&&intval($b->precision)!==0)throw new CreditException("Credit precision must remain zero.");if(isset($b->allow_negative_balance)&&CreditRules::truthy($b->allow_negative_balance))throw new CreditException("Negative user balances are not supported.");return$this->save("davvag_credit_program",$b,array("code","name","description","symbol","precision","timezone","allow_negative_balance","spending_policy","purchase_available","reward_available","coupon_available","purchased_credits_expire","default_reward_expiry_days","status"));});}
    public function postSavePackage($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);CreditRules::amount(CreditServiceSupport::value($b,"credit_amount",0));if(intval(CreditServiceSupport::value($b,"price_minor",-1))<0)throw new CreditException("Package price cannot be negative.");$configured=(new CreditCurrencyAdapter())->requireActive(CreditServiceSupport::value($b,"currency",""));$b->currency=$configured->code;return$this->save("davvag_credit_package",$b,array("program_id","package_code","title","description","credit_amount","bonus_credit_amount","price_minor","currency","payment_channel","provider_product_id","purchase_limit_per_profile","first_purchase_only","active_from","active_until","sort_order","status"));});}
    public function postSaveRewardRule($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);CreditRules::amount(CreditServiceSupport::value($b,"credit_amount",0));return$this->save("davvag_credit_reward_rule",$b,array("program_id","rule_code","title","cadence","award_mode","credit_amount","timezone","week_start_day","month_claim_day","claim_window_hours","eligibility_json","expiry_days","active_from","active_until","status"));});}
    public function postSaveCouponCampaign($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);CreditRules::amount(CreditServiceSupport::value($b,"credit_amount",0));return$this->save("davvag_credit_coupon_campaign",$b,array("program_id","campaign_code","coupon_type","name","description","credit_amount","total_redemption_limit","per_profile_limit","first_time_only","minimum_account_age_days","eligible_group_ids_json","active_from","active_until","credit_expiry_days","status"));});}
    public function postGenerateCoupons($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return array("codes"=>(new CreditCouponService())->generate(CreditServiceSupport::value($b,"campaign_id",0),CreditServiceSupport::value($b,"count",1),CreditServiceSupport::value($b,"maximum_redemptions",1),CreditServiceSupport::value($b,"assigned_profile_id",0),CreditServiceSupport::value($b,"expires_at",null)),"warning"=>"Plain coupon codes are returned once. Store them securely.");});}
    public function postWallets($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);$db=(new CreditLedgerService())->database();$limit=max(1,min(200,intval(CreditServiceSupport::value($b,"limit",100))));return$db->all("SELECT * FROM davvag_credit_wallet WHERE wallet_type='USER_WALLET' ORDER BY id DESC LIMIT ?","i",array($limit));});}
    public function postLedger($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);$db=(new CreditLedgerService())->database();$limit=max(1,min(200,intval(CreditServiceSupport::value($b,"limit",100))));return$db->all("SELECT t.*,COUNT(e.id) entry_count FROM davvag_credit_transaction t LEFT JOIN davvag_credit_entry e ON e.transaction_id=t.id GROUP BY t.id ORDER BY t.id DESC LIMIT ?","i",array($limit));});}
    public function postGrant($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return(new CreditLedgerService())->credit(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,"davvag-credit-points-admin","admin-adjustment",CreditServiceSupport::value($b,"reference_id","grant"),CreditServiceSupport::value($b,"description","Administrator credit grant")),"ADMIN",CreditServiceSupport::value($b,"expires_at",null));});}
    public function postDebit($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return(new CreditLedgerService())->debit(CreditServiceSupport::value($b,"profile_id",0),CreditServiceSupport::value($b,"amount",0),CreditServiceSupport::context($b,"davvag-credit-points-admin","admin-adjustment",CreditServiceSupport::value($b,"reference_id","debit"),CreditServiceSupport::value($b,"description","Administrator credit debit")));});}
    public function postSuspendWallet($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);$db=(new CreditLedgerService())->database();$id=intval(CreditServiceSupport::value($b,"wallet_id",0));$status=CreditRules::truthy(CreditServiceSupport::value($b,"suspended",true))?"SUSPENDED":"ACTIVE";$db->updateById("davvag_credit_wallet",$id,array("status"=>$status,"suspended_reason"=>CreditServiceSupport::value($b,"reason","")));return$db->one("SELECT * FROM davvag_credit_wallet WHERE id=?","i",array($id));});}
    public function postReverse($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return(new CreditLedgerService())->reverse(CreditServiceSupport::value($b,"transaction_id",0),CreditServiceSupport::context($b,"davvag-credit-points-admin","credit-reversal",CreditServiceSupport::value($b,"transaction_id",0),CreditServiceSupport::value($b,"description","Administrator reversal")));});}
    public function postReconcile($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return(new CreditLedgerService())->reconcile(CreditServiceSupport::value($b,"wallet_id",0));});}
    public function postProcessExpirations($req,$res){return$this->call($res,function()use($req){$b=$this->body($req);return(new CreditLedgerService())->expireDueLots(CreditServiceSupport::value($b,"limit",100));});}
}
?>
